const countriesList = [
  'Afghanistan.png',
  'Albania.png',
  'Algeria.png',
  'Andorra.png',
  'Antigua-and-Barbuda.png',
  'Argentina.png',
  'Armenia.png',
  'Australia.png',
  'Austria.png',
  'Azerbaijan.png',
  'Bahamas.png',
  'Bahrain.png',
  'Bangladesh.png',
  'Barbados.png',
  'Belarus.png',
  'Belgium.png',
  'Belize.png',
  'Benin.png',
  'Bhutan.png',
  'Bolivia.png',
  'Bosnia-and-Herzegovina.png',
  'Botswana.png',
  'Brazil.png',
  'Brunei.png',
  'Bulgaria.png',
  'Burkina-Faso.png',
  'Burundi.png',
  'Cambodia.png',
  'Cameroon.png',
  'Canada.png',
  'Cape-Verde.png',
  'Central-African-Republic.png',
  'Chad.png',
  'Chile.png',
  'China.png',
  'Colombia.png',
  'Comoros.png',
  'Congo-(Democratic).png',
  'Congo-(Republic).png',
  'Costa-Rica.png',
  'Cote-d\'Ivoire.png',
  'Croatia.png',
  'Cuba.png',
  'Cyprus.png',
  'Czech-Republic.png',
  'Denmark.png',
  'Djibouti.png',
  'Dominica.png',
  'Dominican-Republic.png',
  'East-Timor.png',
  'Ecuador.png',
  'Egypt.png',
  'El-Salvador.png',
  'Equatorial-Guinea.png',
  'Eritrea.png',
  'Estonia.png',
  'Ethiopia.png',
  'Fiji.png',
  'Finland.png',
  'France.png',
  'Gabon.png',
  'Gambia.png',
  'Georgia.png',
  'Germany.png',
  'Ghana.png',
  'Greece.png',
  'Grenada.png',
  'Guatemala.png',
  'Guinea-Bissau.png',
  'Guinea.png',
  'Guyana.png',
  'Haiti.png',
  'Honduras.png',
  'Hungary.png',
  'Iceland.png',
  'India.png',
  'Indonesia.png',
  'Iran.png',
  'Iraq.png',
  'Ireland.png',
  'Israel.png',
  'Italy.png',
  'Jamaica.png',
  'Japan.png',
  'Jordan.png',
  'Kazakhstan.png',
  'Kenya.png',
  'Kiribati.png',
  'Korea,-North.png',
  'Korea,-South.png',
  'Kosovo.png',
  'Kuwait.png',
  'Kyrgyzstan.png',
  'Laos.png',
  'Latvia.png',
  'Lebanon.png',
  'Lesotho.png',
  'Liberia.png',
  'Libya.png',
  'Liechtenstein.png',
  'Lithuania.png',
  'Luxembourg.png',
  'Macedonia.png',
  'Madagascar.png',
  'Malawi.png',
  'Malaysia.png',
  'Maldives.png',
  'Mali.png',
  'Malta.png',
  'Marshall-Islands.png',
  'Mauritania.png',
  'Mauritius.png',
  'Mexico.png',
  'Micronesia-(Federated).png',
  'Moldova.png',
  'Monaco.png',
  'Mongolia.png',
  'Montenegro.png',
  'Morocco.png',
  'Mozambique.png',
  'Myanmar.png',
  'Namibia.png',
  'Nauru.png',
  'Nepal.png',
  'Netherlands.png',
  'New-Zealand.png',
  'Nicaragua.png',
  'Niger.png',
  'Nigeria.png',
  'Norway.png',
  'Oman.png',
  'Pakistan.png',
  'Palau.png',
  'Panama.png',
  'Papua-New-Guinea.png',
  'Paraguay.png',
  'Peru.png',
  'Philippines.png',
  'Poland.png',
  'Portugal.png',
  'Qatar.png',
  'Romania.png',
  'Russia.png',
  'Rwanda.png',
  'Saint-Kitts-and-Nevis.png',
  'Saint-Lucia.png',
  'Saint-Vincent-and-the-Grenadines.png',
  'Samoa.png',
  'San-Marino.png',
  'Sao-Tome-and-Principe.png',
  'Saudi-Arabia.png',
  'Senegal.png',
  'Serbia.png',
  'Seychelles.png',
  'Sierra-Leone.png',
  'Singapore.png',
  'Slovakia.png',
  'Slovenia.png',
  'Solomon-Islands.png',
  'Somalia.png',
  'South-Africa.png',
  'South-Sudan.png',
  'Spain.png',
  'Sri-Lanka.png',
  'Sudan.png',
  'Suriname.png',
  'Swaziland.png',
  'Sweden.png',
  'Switzerland.png',
  'Syria.png',
  'Taiwan.png',
  'Tajikistan.png',
  'Tanzania.png',
  'Thailand.png',
  'Togo.png',
  'Tonga.png',
  'Trinidad-and-Tobago.png',
  'Tunisia.png',
  'Turkey.png',
  'Turkmenistan.png',
  'Tuvalu.png',
  'Uganda.png',
  'Ukraine.png',
  'United-Arab-Emirates.png',
  'United-Kingdom.png',
  'United-States-of-America.png',
  'Uruguay.png',
  'Uzbekistan.png',
  'Vanuatu.png',
  'Vatican-City.png',
  'Venezuela.png',
  'Vietnam.png',
  'Yemen.png',
  'Zambia.png',
  'Zimbabwe.png',
];

const countries = function generateCountries() {
  const arr = [];
  for (let i = 0; i < 195; i++) {
    const countryName = countriesList[i].slice(0, -4);
    const totalCases = Math.round(1000 + Math.random() * 20000);
    const totalDeaths = Math.round(100 + Math.random() * 2000);
    const totalRecovered = Math.round(1000 + Math.random() * 15000);
    const totalCasesPerHundreds = Math.round(0.01 + Math.random() * 0.20);
    const totalDeathsPerHundreds = Math.round(0.001 + Math.random() * 0.02);
    const totalRecoveredPerHundreds = Math.round(0.01 + Math.random() * 0.15);
    const lastCases = Math.round(10 + Math.random() * 200);
    const lastDeaths = Math.round(1 + Math.random() * 20);
    const lastRecovered = Math.round(10 + Math.random() * 150);
    const lastCasesPerHundreds = Math.round(0.0001 + Math.random() * 0.0020);
    const lastDeathsPerHundreds = Math.round(0.00001 + Math.random() * 0.0002);
    const lastRecoveredPerHundreds = Math.round(0.0001 + Math.random() * 0.0015);
    const coordinates = [
      Math.round(-90 + Math.random() * 180),
      Math.round(-180 + Math.random() * 360),
    ];
    const flagPath = `./assets/img/flags/${countriesList[i]};`;
    const country = {
      countryName,
      coordinates,
      flagPath,
      index: {
        totalCases,
        totalDeaths,
        totalRecovered,
        totalCasesPerHundreds,
        totalDeathsPerHundreds,
        totalRecoveredPerHundreds,
        lastCases,
        lastDeaths,
        lastRecovered,
        lastCasesPerHundreds,
        lastDeathsPerHundreds,
        lastRecoveredPerHundreds,
      },
    };
    arr.push(country);
  }
  return arr;
};

export default countries();
